count_odd_bits : count_odd_bits.o
	gcc -g -Wall -ansi -pedantic count_odd_bits.o -o count_odd_bits

count_odd_bits.o : count_odd_bits.c
	gcc -c -Wall -ansi -pedantic count_odd_bits.c -o count_odd_bits.o
